openapi: 3.0.2
info:
  title:
     Fn::Sub: "${AWS::StackName} - PostOffice Stub Service"
  version: 1.0.0

tags:
  - name: Public Endpoints
    description: Endpoints accessible by the public domain

paths:
  /postoffice/v1/locations/search:
    post:
      tags:
        - Backend Endpoint for Post Office API
      summary: Mock the Post Office location API
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LocationSearchPayload"
        required: true
      responses:
        200:
          description: Locations
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LocationSearchResponse"
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        429:
          $ref: "#/components/responses/429"
        500:
          $ref: "#/components/responses/500"
        503:
          $ref: "#/components/responses/503"
      x-amazon-apigateway-request-validator: "both"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:Post-Office-Stub-${AWS::StackName}:live/invocations
        responses:
          default:
            statusCode: "201"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"

components:
  ## ---------------------
  ## Schema Definitions
  ## ---------------------
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              property:
                type: string
              message:
                type: string
            required:
              - property
              - message
      required:
        - code
        - message

    LocationSearchPayload:
      type: object
      description: Location Search Payload
      required:
        - searchString
        - productFilter
      properties:
          searchString:
            type: string
            example: SW1A 0AA
            description: >-
              The postcode used for PO location search
          productFilter: 
            type: array
            items:
              type: string
            minItems: 1
            example: ["50321"]
            description: >- 
              Filters out Post Office branches by products they support. “50321” is the code for In-Branch Verification.

    LocationSearchResponse:
      type: object
      description: Location Search Response
      properties:
        metadata:
          type: object
      required:
        - metadata

  ## ---------------------
  ## Response Definitions
  ## ---------------------
  responses:
    400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            PAYLOAD_VALIDATION:
              $ref: "#/components/examples/PayloadValidationError"
            MALFORMED_DIGEST:
              $ref: "#/components/examples/MalformedRequestDigestError"
            MALFORMED_TOKEN:
              $ref: "#/components/examples/MalformedRequestTokenError"
    403:
      description: Auth Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            SCHEME_NOT_FOUND:
              $ref: "#/components/examples/SchemeNotFoundError"
            SCHEME_VALIDATION_REQUIREMENT_NOT_FOUND:
              $ref: "#/components/examples/SchemeValidationRequirementNotFoundError"
    429:
      description: Too Many Requests Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            TOO_MANY_REQUESTS:
              $ref: "#/components/examples/TooManyRequestsError"
    500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            SERVER_ERROR:
              $ref: "#/components/examples/UnexpectedServerError"
    503:
      description: Service Unavailable
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            TEMPORARILY_UNAVAILABLE:
              $ref: "#/components/examples/TemporarilyUnavailableError"
  ## ---------------------
  ## Example Definitions
  ## ---------------------
  examples:
    PayloadValidationError:
      value:
        code: PAYLOAD_VALIDATION
        message: There were errors validating the payload
        errors:
          - property: The JSON property name
            message: The error message associated with the property
    MalformedRequestDigestError:
      value:
        code: MALFORMED_REQUEST
        errors:
          - property: header.X-Yoti-Auth-Digest
            message: must not be null or empty
    MalformedRequestTokenError:
      value:
        code: MALFORMED_REQUEST
        errors:
          - property: header.X-Yoti-Auth-Token
            message: must not be null or empty
    SchemeNotFoundError:
      value:
        code: SCHEME_NOT_FOUND
        message: No scheme found that matches provided scheme name
    SchemeValidationRequirementNotFoundError:
      value:
        code: SCHEME_VALIDATION_REQUIREMENT_NOT_FOUND
        message: No scheme validation found for requested issuing country and/or document type
    TooManyRequestsError:
      value:
        code: TOO_MANY_REQUESTS
        message: Exceeded permissible limits
    UnexpectedServerError:
      value:
        code: SERVER_ERROR
        message: An unexpected error occurred on the server
    TemporarilyUnavailableError:
      value:
        code: TEMPORARILY_UNAVAILABLE
        message: Unable to complete your request right now.  Please try again later